services:
  backend1:
    image: samdox/backend:latest
    container_name: backend1
    restart: on-failure
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@proxysql:6133/${POSTGRES_DB}?schema=public
      JWT_SECRET: ${JWT_SECRET}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - sam-network

  backend2:
    image: samdox/backend:latest
    container_name: backend2
    restart: on-failure
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
    environment:
      PORT: 8001
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@proxysql:6133/${POSTGRES_DB}?schema=public
      JWT_SECRET: ${JWT_SECRET}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/health"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - sam-network

networks:
  sam-network:
    external: true