services:
  backend1:
    image: samdox/backend:latest
    container_name: backend1
    restart: on-failure
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
    restart: on-failure
    deploy:
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@proxysql:6133/${POSTGRES_DB}?schema=public
      JWT_SECRET: ${JWT_SECRET}
    networks:
      - sam-network

  backend2:
    image: samdox/backend:latest
    container_name: backend2
    restart: on-failure
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
    restart: on-failure
    deploy:
    environment:
      PORT: 8001
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@proxysql:6133/${POSTGRES_DB}?schema=public
      JWT_SECRET: ${JWT_SECRET}
    networks:
      - sam-network

networks:
  sam-network:
    external: true