services:
  db:
    image: postgres:17
    container_name: postgres_db
    restart: on-failure
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1G
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - sam-network

  proxysql:
    build:
      context: .
      dockerfile: proxysql.Dockerfile
    container_name: proxysql
    ports:
      - "6133:6133"
      - "6132:6132"
    volumes:
      - proxysql-data:/var/lib/proxysql
    depends_on:
      - db
    command: [ "proxysql", "-f", "/etc/proxysql.cnf", "--reload" ]
    networks:
      - sam-network

networks:
  sam-network:
    external: true

volumes:
  postgres-data:
    external: true
    name: login-backend_postgres-data
  proxysql-data:
    external: true
    name: login-backend_proxysql-data